routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::post('posts/changeStatus', array('as' => 'changeStatus', 'uses' => 'AdminProductController@changeStatus'));
Route::resource('/ordermanagement', 'AdminOrderController');
Route::post('/ordermanagement/change-status', 'AdminOrderController@changeOrderStatus');
Route::get('/viewshoppingcart', 'UserManagementController@shopppingcart');
Route::get('/viewdetails/{id}', 'UserManagementController@viewdetails');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/show', 'HomeController@show')->name('search');
Route::group(['middleware'=>['admin']], function(){
Route::resource('admin/authors', 'AdminAuthorController',array('as'=>'admin'));
Route::resource('admin/languages', 'AdminLanguageController',array('as'=>'admin'));
Route::resource('admin/types', 'AdminTypeController',array('as'=>'admin'));
Route::resource('admin/publishers', 'AdminPublisherController',array('as'=>'admin'));
Route::resource('admin/products', 'AdminProductsController',array('as'=>'admin'));
Route::resource('admin/users', 'AdminUsersController' ,array('as'=>'admin'));
Route::get('admin/{id}', 'UserManagementController@show');
Route::post('admin/products/{id}/edit/deleteImageProduct', 'AdminProductsController@deleteImageProduct')->name('delete-image');

});
Route::resource('/', 'HomeController');
Route::post('/product_detail/commentProduct', 'HomeController@commentProduct')->name('comment_roduct');
Route::post('/all_product/sortProduct', 'HomeController@sortProduct')->name('sort_product');
Route::get('/product_detail/{id}', 'HomeController@productDetail')->name('product_detail');
Route::resource('/home', 'HomeController');
Route::get('/author_detail/{id}/','MenuController@menuAuthors')->name('author_detail');
Route::get('/type_detail/{id}/','MenuController@menuTypes')->name('type_detail');
Route::get('/language_detail/{id}/','MenuController@menuLanguages')->name('language_detail');
Route::get('/publisher_detail/{id}/','MenuController@menuPublishers')->name('publisher_detail');
Route::get('/all_product', 'HomeController@allProduct')->name('all_product');
Route::get('/checkout', 'HomeController@checkOut')->name('checkout');
Route::resource('user/management', 'UserManagementController');
Route::get('user/{id}', 'UserManagementController@show');
Route::get('user/edit/{id}', 'UserManagementController@edit');
Route::put('user/update/{id}', 'UserManagementController@update');
Route::get('user/wishlist/{id}', 'UserManagementController@viewWishlist',array('as' => 'management.wishlist'));
Route::get('user/wishlist/add/{pid}', 'UserManagementController@addToWishlist',array('as' => 'management.wishlist.add'));
Route::get('user/wishlist/delete/{pid}', 'UserManagementController@deleteProductWishlist',array('as' => 'management.wishlist.delete'));
Route::get('/add-to-cart/{id}', [
    'uses' => 'ProductController@getAddToCart',
]);
Route::get('/delete-cart-product/{id}', [
    'uses' => 'ProductController@removeItem',
    'as' => 'product.removeItem'
]);

Route::get('/delete-cart/', [
    'uses' => 'ProductController@removeCart',
]);

Route::post('/shopping-cart/change-quantity', [
    'uses' => 'ProductController@changeProductQuantity',
    'as' => 'product.changeProductQuantity'
]);

Route::get('shopping-cart', [
    'uses' => 'ProductController@getCart',
    'as' => 'product.shoppingcart'
]);
Route::get('/contact-us', 'HomeController@contactUs')->name('contact_us');
Route::post('/send-feed-back', 'HomeController@sendFeedback')->name('send_feed_back');
Route::get('/about-us', 'HomeController@aboutUs')->name('about_us');
Auth::routes();
Route::resource('checkout', 'OrderController');

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Session;
use App\Book;
use App\Cart;

class ProductController extends Controller {
    public function getCart() {
        if (!Session::has('cart')) {
            $types = \App\Type::all();
            $languages = \App\Language::all();
            $publishers = \App\Publisher::all();
            $authors = \App\Author::all();
            return view('shop.cart', ['products' => null], compact('types', 'languages', 'publishers', 'authors'));
        }
        $oldCart = Session::get('cart');
        $cart = new Cart($oldCart);
        $types = \App\Type::all();
        $languages = \App\Language::all();
        $publishers = \App\Publisher::all();
        $authors = \App\Author::all();
        return view('shop.cart', ['products' => $cart->items, 'totalPrice' => $cart->totalPrice], compact('types', 'languages', 'publishers', 'authors'));
    }
     public function getCheckOut() {
        if (!Session::has('cart')) {
            $types = \App\Type::all();
            $languages = \App\Language::all();
            $publishers = \App\Publisher::all();
            $authors = \App\Author::all();
            return view('shop.checkout', ['products' => null], compact('types', 'languages', 'publishers', 'authors'));
        }
        $oldCart = Session::get('cart');
        $cart = new Cart($oldCart);
        $types = \App\Type::all();
        $languages = \App\Language::all();
        $publishers = \App\Publisher::all();
        $authors = \App\Author::all();
        return view('shop.checkout', ['products' => $cart->items, 'totalPrice' => $cart->totalPrice], compact('types', 'languages', 'publishers', 'authors'));
    }

    public function getIndex() {
        $products = Book::orderBy('created_at', 'ASC') - get()->paginate(12);
        return view('home', compact('products'));
    }

    public function getAddToCart($id) {
        $product = Book::with('pictures')->findOrFail($id);
        $oldCart = Session::has('cart') ? Session::get('cart') : null;
        $cart = new Cart($oldCart);
        $cart->add($product, $product->id);
        session()->put('cart', $cart);
        return response()->json(Session::get('cart'));
    }
//
//    public function getCheckout() {
//        if (!Session::has('cart')) {
//            return view('cart', ['products' => null]);
//        }
//        $oldCart = Session::get('cart');
//        $cart = new Cart($oldCart);
//        $total = $cart->totalPrice;
//        return view('checkout', ['total' => $total]);
//    }

    public function changeProductQuantity(Request $request) {

        $oldCart = Session::has('cart') ? Session::get('cart') : null;
        $cart = new Cart($oldCart);
        $cart->changeProductQuantity($request->id, $request->quantity);
        session()->put('cart', $cart);
        return response()->json(Session::get('cart'));
    }

    
    public function removeItem($id) {
        $oldCart = Session::has('cart') ? Session::get('cart') : null;
        $cart = new Cart($oldCart);
        $cart->removeItem($id);
        if (count($cart->items) > 0) {
            Session::put('cart', $cart);
        } else {
            Session::forget('cart');
        }
        return response()->json(session()->has('cart') ? session()->get('cart') : null);
    }

    public function removeCart() {
        $remove = session()->pull('cart', 'default');
        return back()->withInput();
    }

}

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
               <meta name="_token" content="{{ csrf_token() }}">
        <meta name="public_path" content="{{ asset('/') }}">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Book store Cpanel</title>
        <!-- Bootstrap core CSS-->
        <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
        <!-- Custom fonts for this template-->
        <link href="{{asset('vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
        <!-- Page level plugin CSS-->
        <link href="{{asset('vendor/datatables/dataTables.bootstrap4.css')}}" rel="stylesheet">
        <!-- Custom styles for this template-->
        <link href="{{asset('css/sb-admin.css')}}" rel="stylesheet">
        @yield('custom_css')
    </head>

    <body class="fixed-nav sticky-footer bg-dark" id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <a class="navbar-brand" href="{{url('/')}}">Book Store</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
                    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Users">
                        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseUsers" data-parent="#exampleAccordion">
                            <i class="fa fa-fw fa-wrench"></i>
                            <span class="nav-link-text">Users Management</span>
                        </a>
                        <ul class="sidenav-second-level collapse" id="collapseUsers">
                            <li>
                                <a href="{{route('admin.users.index')}}">View Users</a>
                            </li>
                            <li>
                                <a href="{{route('admin.users.create')}}">Create User</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Products">
                        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
                            <i class="fa fa-fw fa-sitemap"></i>
                            <span class="nav-link-text">Products Management</span>
                        </a>
                        <ul class="sidenav-second-level collapse" id="collapseMulti">

                            <li>
                                <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2">Products</a>
                                <ul class="sidenav-third-level collapse" id="collapseMulti2">
                                    <li>
                                        <a href="{{route('admin.products.index')}}">View Products</a>
                                    </li>
                                    <li>
                                        <a href="{{route('admin.products.create')}}">Create Product</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2">Types</a>
                                <ul class="sidenav-third-level collapse" id="collapseMulti2">
                                    <li>
                                        <a href="{{route('admin.types.index')}}">View Types</a>
                                    </li>
                                    <li>
                                        <a href="{{route('admin.types.create')}}">Create Types</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti3">Languages</a>
                                <ul class="sidenav-third-level collapse" id="collapseMulti3">
                                    <li>
                                        <a href="{{route('admin.languages.index')}}">View Languages</a>
                                    </li>
                                    <li>
                                        <a href="{{route('admin.languages.create')}}">Create Language</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti4">Authors</a>
                                <ul class="sidenav-third-level collapse" id="collapseMulti4">
                                    <li>
                                        <a href="{{route('admin.authors.index')}}">View Authors</a>
                                    </li>
                                    <li>
                                        <a href="{{route('admin.authors.create')}}">Create Authors</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti5">Publishers</a>
                                <ul class="sidenav-third-level collapse" id="collapseMulti5">
                                    <li>
                                        <a href="{{route('admin.publishers.index')}}">View Publishers</a>
                                    </li>
                                    <li>
                                        <a href="{{route('admin.publishers.create')}}">Create Publisher</a>
                                    </li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">

                        <a class="nav-link" href="{{url('/ordermanagement')}}">
                            <i class="fa fa-fw fa-link"></i>
                            <span class="nav-link-text">Order Management</span>
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav sidenav-toggler">
                    <li class="nav-item">
                        <a class="nav-link text-center" id="sidenavToggler">
                            <i class="fa fa-fw fa-angle-left"></i>
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="content-wrapper">
            <div class="container-fluid">
                @yield('content')
            </div>
            <a class="scroll-to-top rounded" href="#page-top">
                <i class="fa fa-angle-up"></i>
            </a>
            <!-- Logout Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                            <a class="btn btn-primary" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">Logout
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Bootstrap core JavaScript-->
            <script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>
            <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
            <!-- Core plugin JavaScript-->
            <script src="{{asset('vendor/jquery-easing/jquery.easing.min.js')}}"></script>
            <!-- Page level plugin JavaScript-->
            <script src="{{asset('vendor/chart.js/Chart.min.js')}}"></script>
            <script src="{{asset('vendor/datatables/jquery.dataTables.js')}}"></script>
            <script src="{{asset('vendor/datatables/dataTables.bootstrap4.js')}}"></script>
            <!-- Custom scripts for all pages-->
            <script src="{{asset('js/sb-admin.min.js')}}"></script>
            <script src="{{asset('js/js.js')}}"></script>
            <!-- Custom scripts for this page-->
            <script src="{{asset('js/sb-admin-datatables.min.js')}}"></script>
                        <script src="{{asset('js/delete_image.js')}}"></script>
            @yield('custom_js')
        </div>
    </body>

</html>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li><a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a></li>
                            <li><a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a></li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/user.blade.php
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Book store Cpanel</title>
        <!-- Bootstrap core CSS-->
        <link href="{{asset('vendor/bootstrap/css/bootstrap.min.css')}}" rel="stylesheet">
        <!-- Custom fonts for this template-->
        <link href="{{asset('vendor/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet" type="text/css">
        <!-- Page level plugin CSS-->
        <link href="{{asset('vendor/datatables/dataTables.bootstrap4.css')}}" rel="stylesheet">
        <!-- Custom styles for this template-->
        <link href="{{asset('css/sb-admin.css')}}" rel="stylesheet">
        @yield('custom_css')
    </head>

    <body class="fixed-nav sticky-footer bg-dark" id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
            <a class="navbar-brand" href="{{url('/')}}">Book Store</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">

                    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Users">
                        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseUsers" data-parent="#exampleAccordion">
                            <i class="fa fa-fw fa-wrench"></i>
                            <span class="nav-link-text">My Account</span>
                        </a>
                        <ul class="sidenav-second-level collapse" id="collapseUsers">
                            <li>
                                <a href="{{url('user').'/'.Auth::user()->id}}">My Account</a>
                            </li>
                            <li>
                                <a href="{{url('user/edit')."/".Auth::user()->id}}">Edit Account</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Products">
                        <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
                            <i class="fa fa-fw fa-sitemap"></i>
                            <span class="nav-link-text">My Order</span>
                        </a>
                        <ul class="sidenav-second-level collapse" id="collapseMulti">
                            <li>
                                <a href="{{url('/viewshoppingcart')}}">View</a>
                            </li>
                        </ul>
                    </li>
                    <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                        <a class="nav-link" href="{{url('user/wishlist/'.Auth::user()->id)}}">
                            <i class="fa fa-fw fa-link"></i>
                            <span class="nav-link-text">Wishlist</span>
                        </a>
                    </li>

                </ul>
                <ul class="navbar-nav sidenav-toggler">
                    <li class="nav-item">
                        <a class="nav-link text-center" id="sidenavToggler">
                            <i class="fa fa-fw fa-angle-left"></i>
                        </a>
                    </li>
                </ul>
                <ul class="navbar-nav ml-auto">

                    <li class="nav-item">
                        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                            <i class="fa fa-fw fa-sign-out"></i>Logout</a>
                    </li>
                </ul>
            </div>
        </nav>
        <div class="content-wrapper">
            <div class="container-fluid">
                @yield('content')
            </div>
            <!-- /.container-fluid-->
            <!-- /.content-wrapper-->
            <footer class="sticky-footer">
                <div class="container">
                    <div class="text-center">
                        <small>Copyright © Your Website 2018</small>
                    </div>
                </div>
            </footer>
            <!-- Scroll to Top Button-->
            <a class="scroll-to-top rounded" href="#page-top">
                <i class="fa fa-angle-up"></i>
            </a>
            <!-- Logout Modal-->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                            <a class="btn btn-primary" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                       document.getElementById('logout-form').submit();">Logout
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Bootstrap core JavaScript-->
            <script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>
            <script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
            <!-- Core plugin JavaScript-->
            <script src="{{asset('vendor/jquery-easing/jquery.easing.min.js')}}"></script>
            <!-- Page level plugin JavaScript-->
            <script src="{{asset('vendor/chart.js/Chart.min.js')}}"></script>
            <script src="{{asset('vendor/datatables/jquery.dataTables.js')}}"></script>
            <script src="{{asset('vendor/datatables/dataTables.bootstrap4.js')}}"></script>
            <!-- Custom scripts for all pages-->
            <script src="{{asset('js/sb-admin.min.js')}}"></script>
            <!-- Custom scripts for this page-->
            <script src="{{asset('js/sb-admin-datatables.min.js')}}"></script>
            @yield('custom_js')
        </div>
    </body>

</html>