routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::post('posts/changeStatus', array('as' => 'changeStatus', 'uses' => 'AdminProductController@changeStatus'));
Route::resource('/ordermanagement', 'AdminOrderController');
Route::post('/ordermanagement/change-status', 'AdminOrderController@changeOrderStatus');
Route::get('/viewshoppingcart', 'UserManagementController@shopppingcart');
Route::get('/viewdetails/{id}', 'UserManagementController@viewdetails');
Route::get('/search', 'HomeController@search')->name('search');
Route::get('/show', 'HomeController@show')->name('search');
Route::group(['middleware'=>['admin']], function(){
Route::resource('admin/authors', 'AdminAuthorController',array('as'=>'admin'));
Route::resource('admin/languages', 'AdminLanguageController',array('as'=>'admin'));
Route::resource('admin/types', 'AdminTypeController',array('as'=>'admin'));
Route::resource('admin/publishers', 'AdminPublisherController',array('as'=>'admin'));
Route::resource('admin/products', 'AdminProductsController',array('as'=>'admin'));
Route::resource('admin/users', 'AdminUsersController' ,array('as'=>'admin'));
Route::get('admin/{id}', 'UserManagementController@show');
Route::post('admin/products/{id}/edit/deleteImageProduct', 'AdminProductsController@deleteImageProduct')->name('delete-image');

});
Route::resource('/', 'HomeController');
Route::post('/product_detail/commentProduct', 'HomeController@commentProduct')->name('comment_roduct');
Route::post('/all_product/sortProduct', 'HomeController@sortProduct')->name('sort_product');
Route::get('/product_detail/{id}', 'HomeController@productDetail')->name('product_detail');
Route::resource('/home', 'HomeController');
Route::get('/author_detail/{id}/','MenuController@menuAuthors')->name('author_detail');
Route::get('/type_detail/{id}/','MenuController@menuTypes')->name('type_detail');
Route::get('/language_detail/{id}/','MenuController@menuLanguages')->name('language_detail');
Route::get('/publisher_detail/{id}/','MenuController@menuPublishers')->name('publisher_detail');
Route::get('/all_product', 'HomeController@allProduct')->name('all_product');
Route::get('/checkout', 'HomeController@checkOut')->name('checkout');
Route::resource('user/management', 'UserManagementController');
Route::get('user/{id}', 'UserManagementController@show');
Route::get('user/edit/{id}', 'UserManagementController@edit');
Route::put('user/update/{id}', 'UserManagementController@update');
Route::get('user/wishlist/{id}', 'UserManagementController@viewWishlist',array('as' => 'management.wishlist'));
Route::get('user/wishlist/add/{pid}', 'UserManagementController@addToWishlist',array('as' => 'management.wishlist.add'));
Route::get('user/wishlist/delete/{pid}', 'UserManagementController@deleteProductWishlist',array('as' => 'management.wishlist.delete'));
Route::get('/add-to-cart/{id}', [
    'uses' => 'ProductController@getAddToCart',
]);
Route::get('/delete-cart-product/{id}', [
    'uses' => 'ProductController@removeItem',
    'as' => 'product.removeItem'
]);

Route::get('/delete-cart/', [
    'uses' => 'ProductController@removeCart',
]);

Route::post('/shopping-cart/change-quantity', [
    'uses' => 'ProductController@changeProductQuantity',
    'as' => 'product.changeProductQuantity'
]);

Route::get('shopping-cart', [
    'uses' => 'ProductController@getCart',
    'as' => 'product.shoppingcart'
]);
Route::get('/contact-us', 'HomeController@contactUs')->name('contact_us');
Route::post('/send-feed-back', 'HomeController@sendFeedback')->name('send_feed_back');
Route::get('/about-us', 'HomeController@aboutUs')->name('about_us');
Auth::routes();
Route::resource('checkout', 'OrderController');

resources/views/admin/types/create.blade.php
@extends('layouts.admin')

@section('content')


    <h1>Type</h1>


    <div class="col-sm-6">
        <form action="{{ route('admin.types.store') }}" method="post">
            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>

            <div class=" form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    <label for="name">name:</label>
                    <input type="text" id="name" name="name" class="form-control" placeholder="Enter type name" value="{{ old('name') }}">
                    <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>        

           
            <div class="form-group">
                <input type="submit" class="btn btn-success" value="Create type" />
            </div>
        </form>
 


    </div>


@endsection

resources/views/admin/types/edit.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Type</h1>


    <div class="col-sm-6">
        <form action="{{ route('admin.types.update', $type->id) }}" method="POST" >
            <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
         <input type="hidden" name="_method" value="PUT">
         <div class=" form-group {{ $errors->has('name') ? 'has-error' : '' }}">
                    <label for="username">Name:</label>
                    <input type="text" id="name" name="name" class="form-control" placeholder="Enter type name" value="{{ $type->name }}">
                    <span class="text-danger">{{ $errors->first('name') }}</span>
            </div>  

        <div class="form-group">
           <input type="submit" class="btn btn-success" value="Update type" />
        </div>
        </form>

    </div>




    <div class="col-sm-6">






    </div>





@stop

resources/views/admin/types/index.blade.php
@extends('layouts.admin')
@section('content')
<div class="container">
<h1>Type</h1>
<div class="col-sm-6">
    <form action="{{ route('admin.types.create')}}">
        <div class="form-group">
            <input type="submit" class="btn btn-success" value="Create" />
        </div>
    </form>
</div>

<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>       
            <th>Created at</th>
            <th>Updated date</th>  
            <th>Edit</th>
            <th>Delete</th>
    </thead>
    <tbody>
        @if($types)
        
        @foreach($types as $type)

        <tr>
            <td>{{$type->id}}</td>
            <td>{{$type->name}}</a></td>
            <td>{{$type->created_at ? $type->created_at->diffForHumans() : 'no date'}}</td>
            <td>{{$type->updated_at ? $type->updated_at->diffForHumans() : 'no date'}}</td>  
            <td>
                <form action="{{route('admin.types.edit',$type->id)}}" >
                    <div class="form-group">
                        <input type="submit" class="btn btn-success" value="Edit" />
                    </div>
                </form>

            </td> 
            <td>  
                <form action="{{ route('admin.types.destroy',$type->id) }}" method="POST" >
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="hidden" name="_token" value="{{ csrf_token() }}"/>
                    <div class="form-group">
                        <input type="submit" class="btn btn-danger" value="Delete" />

                    </div>
                </form>
            </td>
        </tr>
        @endforeach

@endif

    </tbody>
</table>
@if (session('response'))
    <div class="alert {{session('response')["status"] == 'success' ?  'alert-success' : 'alert-danger'}}">
    <strong>{{session('response')["message"]}}</strong> 
  </div>
    @endif
<div class="row">
    <div style="position: absolute;left: 50%;margin-top: -10px;">
        {{ $types->render() }}
    </div>
</div>
</div>
</div>




@stop